### ISSUE TITLE
Base64 Issue

### ISSUE THREAD

**Issue by cooltrooper** [adamtabrams/change#2]
```shell
base64: invalid option -- 'D'
Try 'base64 --help' for more information.
{
  "message": "Bad credentials",
  "documentation_url": "https://docs.github.com/rest"
}
```

changing it to -d in the script solves the problem, line 109?

**Comment by adamtabrams** [comment]
@cooltrooper Thanks for creating an issue for this! My system is actually using the BSD version of the `base64` program which is why I used '-D' for decoding:
```man
> base64 --help                                               
Usage:	base64 [-hvD] [-b num] [-i in_file] [-o out_file]
  -h, --help     display this message
  -D, --decode   decodes input
  -b, --break    break encoded string into num character lines
  -i, --input    input file (default: "-" for stdin)
  -o, --output   output file (default: "-" for stdout)
  ```
I didn't realize that the linux version uses a different argument.  It looks like using `--decode` should give the proper behavior across both systems. I'll change it to that.
