### ISSUE TITLE
Support remote name configuration

### ISSUE THREAD

**Issue by rcisterna** [adamtabrams/change#21]
**Existing Problem**
Currently, `change` only support a remote named `origin`. So, if I have only one remote with a different name, it fails with an exit code 1, and a message saying `remote origin url isn't set for this repo`.

**First Solution**
It would be nice if, instead, `change` worked something like this:
- If I have only one remote, `change` should use that one.
- If I have more than one remote, try to use `origin` or fail just the way it fails now.
- Allow to configure the name of the remote for all my repos (with an environment variable like `CHANGE_REMOTE_NAME` for example), or a `.env` like file (that could be called `.change`) to select the name of preferred remote.

**Alternative Solutions**
I actually don't have any more ideas.

**Further Explaination**
<img width="792" alt="Screen Shot 2022-07-12 at 20 29 58" src="https://user-images.githubusercontent.com/1643949/178623355-c8ce28a1-c6c4-49da-9ede-d0a84c40af0b.png">

**Comment by rcisterna** [comment]
If you are open to it, I can help you with this 😁.

**Comment by adamtabrams** [comment]
I've created a PR that attempts to support this, but with a different strategy. Instead of adding logic to handle different remotes (which I couldn't find a robust way to parse) or adding a config file, this just uses urls instead (as supplied by `git ls-remote --get-url`).

@rcisterna I'm not sure if this use case is still relevant to you. But if it is, would you be willing to test if these code changes fix the issue?

**Comment by rcisterna** [comment]
Hi @adamtabrams! It's currently not relevant to me, but it will be a pleasure to help you test the changes.

**Comment by adamtabrams** [comment]
Does the version [here](https://github.com/adamtabrams/change/blob/4ab54980b020fb9403b8392688d2ba8f8a86e6f6/change) behave as you expect for branches with multiple remotes? Also when there's only one remote, but it isn't named `origin`?
